### ISSUE TITLE
Add `repository` key to Cargo.toml

### ISSUE THREAD

**Issue by dvdplm** [fckt/parity-hash#7]

**Comment by Robbepop** [comment]
Done by https://github.com/fckt/parity-hash/pull/13.
Has to be merged, yet.

However, please note that you should use the `fixed-hash` of `paritytech/parity-common` instead of `parity-hash` repo if possible.

**Comment by Robbepop** [comment]
Can be closed now as of https://github.com/fckt/parity-hash/commit/476fa51d9c6c247885e8933efb521b9681a8ba90.
