### ISSUE TITLE
Relation to `fixed-hash`

### ISSUE THREAD

**Issue by dvdplm** [fckt/parity-hash#8]
How is this crate related to `fixed-hash` from https://github.com/paritytech/parity-common/ ? Seems like it's overlapping.

**Comment by Robbepop** [comment]
As far as I know `parity-hash` was moved into `paritytech/parity-common` as `fixed-hash` with slightly reduced interface. So `paritytech/parity-common/fixed-hash` should be preferred to `parity-hash`.

**Comment by dvdplm** [comment]
Indeed! Closing this. ;)
